name: Add PR to roadmaps

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  add-to-roadmaps:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current year
        id: current_year
        run: echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV
      - 
        name: Get Pull Request Details
        id: pr_details
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const prHeadRef = context.payload.pull_request.head.ref;
            const prOwner = context.payload.pull_request.user.login;
            const prRepository = context.payload.repository.full_name;
            const prTitle = context.payload.pull_request.title;
            const prBody = context.payload.pull_request.body;
            const prUrl = context.payload.pull_request.html_url;

            // Expresiones regulares para extraer los campos
            const allyRegex = /## Aliado Afectado\s*([^\n]+)/i;
            const typeFeatRegex = /-\s*\[x\]\s*(.*)\s*\(/i;
            const testerRegex = /- Encargad@s: (.*)/i;
            const taskAsanaRegex = /\[Enlace de la tarea en Asana\]\((.*)\)/i;

            const title = prTitle;
            const branch = prHeadRef;
            const owner = prOwner;
            const repository = prRepository;
            const pullRequestUrl = prUrl;
            const ally = allyRegex.exec(prBody) ? allyRegex.exec(prBody)[1].trim() : "N/A";
            const typeFeat = typeFeatRegex.exec(prBody) ? typeFeatRegex.exec(prBody)[1].trim() : "N/A";
            const tester = testerRegex.exec(prBody) ? testerRegex.exec(prBody)[1].trim() : "N/A";
            const taskAsana = taskAsanaRegex.exec(prBody) ? taskAsanaRegex.exec(prBody)[1].trim() : "N/A";

            core.setOutput('title', title);
            core.setOutput('ally', ally);
            core.setOutput('owner', owner);
            core.setOutput('typeFeat', typeFeat);
            core.setOutput('repository', repository);
            core.setOutput('branch', branch);
            core.setOutput('pullRequestUrl', pullRequestUrl);
            core.setOutput('tester', tester);
            core.setOutput('taskAsana', taskAsana);
      - 
        name: Add PR to roadmaps
        id: "update_worksheet"
        uses: jroehl/gsheet.action@v2.0.0
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        with:
          spreadsheetId: ${{ vars.GSHEET_SPREADSHEET_ID }}
          commands: |
            [
              { 
                "command": "appendData",
                "args": {
                  "worksheetTitle": "${{ vars.GSHEET_WORKSHEET_NAME }}${{ env.YEAR }}",
                  "minCol": 1,
                  "data": [[
                    "${{ steps.pr_details.outputs.title }}",
                    "${{ steps.pr_details.outputs.ally }}",
                    "${{ steps.pr_details.outputs.owner }}",
                    "${{ steps.pr_details.outputs.typeFeat }}",
                    "${{ steps.pr_details.outputs.repository }}",
                    "${{ steps.pr_details.outputs.branch }}",
                    "${{ steps.pr_details.outputs.pullRequestUrl }}",
                    "${{ steps.pr_details.outputs.tester }}",
                    "",
                    "${{ steps.pr_details.outputs.taskAsana }}"
                  ]]
                }
              }
            ]
